version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Security Audit Dependencies
          command: ./scripts/audit_dependencies.sh
      - run:
          name: Build code
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: ./coverage
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?/
